## OR 데이터 인식

# 사이킷 런의 디자인 패턴

- 데이터 읽기
- 모델 객체 생성
- 모델 학습
- 예측
- 성능 평가

In [1]:
from sklearn.linear_model import Perceptron

In [2]:
#훈련 집합 구축
x=[[0,0],[0,1],[1,0],[1,1]]
y=[-1,1,1,1]

In [4]:
#fit 함수로 perceptron 학습
p=Perceptron()    #perceptron 함수 호출하여 객체 p에 저장
p.fit(x,y)        #fit 함수로 x와 y에 대한 학습을 수행한다.

Perceptron()

In [5]:
print("학습된 퍼셉트론의 매개변수: ",p.coef_,p.intercept_)  #학습을 마친 퍼셉트론의 매개변수, 즉 가중치 w0,w1,w2를 출력한다.
#coef_: w1,w2 , intercept_ : w0

학습된 퍼셉트론의 매개변수:  [[2. 2.]] [-1.]


In [6]:
print("훈련집합에 대한 예측: ",p.predict(x)) #predict 함수를 사용해 훈련집합x를 테스트용으로 간주하고 예측을 수행한다.

훈련집합에 대한 예측:  [-1  1  1  1]


In [7]:
print("정확률 측정: ",p.score(x,y)*100,"%") #score 함수는 x를 퍼셉트론으로 예측한 값과 y(레이블)을 비교하여 맞힌 샘플 개수를 세어 정확률을 계산한다.

정확률 측정:  100.0 %


## 필기 숫자 데이터 인식

In [1]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
#데이터셋을 읽고 훈련집합과 테스트집합으로 분할
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.6) #train_test_split 함수

In [3]:
#fit 함수로 Perceptron 학습
p=Perceptron(max_iter=100,eta0=0.001,verbose=0) #모델 객체 생성 :sklearn의 perceptron 함수
p.fit(x_train,y_train) #digit 데이터로 모델링 -> 모델 학습

Perceptron(eta0=0.001, max_iter=100)

In [4]:
res=p.predict(x_test) #테스트 집합으로 예측 > 학습된 모델로 예측

### 성능 측정

In [5]:
#혼동 행렬
conf=np.zeros((10,10))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

[[66.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 61.  0.  0.  1.  0.  0.  0.  0.  1.]
 [ 0.  0. 75.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0. 63.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 71.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  4.  0. 79.  0.  0.  0.  2.]
 [ 0.  1.  0.  0.  1.  0. 65.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 62.  1.  0.]
 [ 0. 14.  2.  4.  2.  1.  1.  1. 70.  5.]
 [ 0.  1.  0.  1.  1.  0.  0.  1.  0. 58.]]


In [8]:
#정확률 계산
no_correct=0
for i in range(10):
    no_correct+=conf[i][i]
accuracy=no_correct/len(res)
print(accuracy*100,"%")

93.18497913769124 %


## 다층 퍼셉트론