In [7]:
text='You say goodbye and I say hello.'

In [8]:
text=text.lower()

In [13]:
text=text.replace('.',' .')
text

'you say goodbye and i say hello .'

In [14]:
words=text.split(' ')

In [15]:
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

### 단어에 id를 부여하고, id의 리스트로 이용할 수 있도록

In [16]:
word_to_id={}
id_to_word={}

In [17]:
for word in words:
    if word not in word_to_id:
        new_id=len(word_to_id)
        word_to_id[word]=new_id
        id_to_word[new_id]=word

In [18]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [19]:
word_to_id

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}

In [20]:
id_to_word[1]

'say'

In [21]:
word_to_id['hello']

5

In [23]:
import numpy as np
corpus=[word_to_id[w] for w in words]
corpus=np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [73]:
def preprocess(text):
    text=text.lower()
    text=text.replace('.',' .')
    words=text.split(' ')
    word_to_id={}
    id_to_word={}
    for word in words:
        if word not in word_to_id:
            new_id=len(word_to_id)
            word_to_id[word]=new_id
            id_to_word[new_id]=word
        
    corpus=np.array([word_to_id[w] for w in words])
    
    return corpus,word_to_id,id_to_word

In [74]:
text='You say goodbye and i say hello.'
corpus,word_to_id,id_to_word=preprocess(text)

In [97]:
import sys
print(sys.path)

['/Users/minjikim/iCloud\xa0Drive(아카이브)/Documents/GitHub/AI-by-PYTHON', '/Users/minjikim/opt/anaconda3/lib/python39.zip', '/Users/minjikim/opt/anaconda3/lib/python3.9', '/Users/minjikim/opt/anaconda3/lib/python3.9/lib-dynload', '', '/Users/minjikim/opt/anaconda3/lib/python3.9/site-packages', '/Users/minjikim/opt/anaconda3/lib/python3.9/site-packages/aeosa', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '/common', '/common/util', '/common/util', '..']


In [99]:
import sys
import numpy as np
from common.util import preprocess
text='You say goodbye and I say hello.'
corpus,word_to_id,id_to_word=preprocess(text)

ModuleNotFoundError: No module named 'common.util'

In [100]:
print(corpus)

[0 1 2 3 4 1 5 6]


In [101]:
print(id_to_word)

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


## 동시 발생 행렬

In [102]:
C=np.array([
    [0,1,0,0,0,0,0],
    [1,0,1,0,1,1,0],
    [0,1,0,1,0,0,0],
    [0,1,0,0,0,0,1],
    [0,0,0,0,0,1,0],
],dtype=np.int32)

In [103]:
print(C[0]) #id가 0인 단어의 벡터 표현

[0 1 0 0 0 0 0]


In [105]:
print(C[word_to_id['say']])

[1 0 1 0 1 1 0]


In [106]:
def creat_co_matrix(corpus,vocab_size,window_size=1):
    corpus_size=len(corpus)
    co_matrix=np.zeros((vocab_size,vocab_size),dtype=np.int32)
    
    for idx,word_id in enumerate(corpus):
        for i in range(1,window_size+1):
            left_idx=idx-i
            right_idx=idx+i
            
            if left_idx>=0:
                left_word_id=corpus[left_idx]
                co_matrix[word_id,left_word_id]+=1
            if right_idx<corpus_size:
                right_word_id=corpus[right_idx]
                co_matrix[word_id,right_word_id]+=1
    return co_matrix

In [108]:
import sys
print(sys.path)

['/Users/minjikim/iCloud\xa0Drive(아카이브)/Documents/GitHub/AI-by-PYTHON', '/Users/minjikim/opt/anaconda3/lib/python39.zip', '/Users/minjikim/opt/anaconda3/lib/python3.9', '/Users/minjikim/opt/anaconda3/lib/python3.9/lib-dynload', '', '/Users/minjikim/opt/anaconda3/lib/python3.9/site-packages', '/Users/minjikim/opt/anaconda3/lib/python3.9/site-packages/aeosa', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '/common', '/common/util', '/common/util', '..']
